// Zeus Terminal — App Version
// Update this file on each deploy
'use strict';

module.exports = {
    version: '1.7.24',
    build: 50,
    date: '2026-04-19',
    changelog: 'Post-v2 batch5 b50 v1.7.24 — Phase 5 complete (AT live ownership leak) + Bug #2 manual live size drift. (1) Phase 5A (abc58be): telemetry for live AT ownership race across server push, client at_update cache, liveApi classify, and AT render filter — zero behavior change, instrumentation only. (2) Phase 5B (4ea0d04): server/services/serverAT.getLivePositions symmetry fix — demo-parity filter includes all mode===live positions except terminal zombies (CLOSED/EMERGENCY_CLOSED/ERROR/LOCK_BLOCKED); prior filter dropped AT-owned positions with transient live.status before exchange sync confirmed. Closes server-side hypothesis: AT live positions were invisible in canonical snapshot right after push. (3) Phase 5C (1f0b23e): client/src/trading/liveApi.ts NEW-branch safe-unknown defaults — when no server AT evidence AND no TP match, use autoTrade=null, sourceMode=unknown instead of autoTrade=false, sourceMode=paper. Manual filter _isManualOwned (autoTrade===false OR sourceMode in {manual,paper}) now rejects unknown → no more AT→Manual leak during the race window before _lastServerPositions arrives. AT filter requires truthy autoTrade → also rejects unknown → positions wait for authoritative classification via upward reclassify (line 235-244). (4) Phase 5D: no-op verified — autotrade.ts:1669-1674 AT render filter already reads useATStore.getState().mode canonical and filters p.mode/p._serverMode correctly; combined with 5C exclusion of unknown, the mode-filter chain is correct. (5) Phase 5E: full sweep green — server syntax OK, tsc 0 errors, vitest 76/76, vite build OK. (6) Bug #2 (b52e428): manual live order $100 opening at $90 — root cause exchange stepSize rounds qty DOWN (Math.floor in exchangeInfo.roundToStep) so client-sent qty shrinks, but client stored pos.size=user-intent while pos.qty=executedQty (mismatched). Fix in marketDataTrading.ts:_executeLiveManualOrder MARKET branch — reconcile pos.size = (executedQty * fillPrice) / lev to actual exchange fill, toast shows actual size, SL/TP use _execQty. Demo-parity: pos.size = actual position notional in both demo (no rounding) and live (post-fill reconciled). Previous: batch4 b49 v1.7.23 (R-cleanup zero-error tsc baseline).'
};
